version: "3.9"
services:
  votify-postgres:
    image: postgres:15.2-alpine
    container_name: votify-postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
        - ./init.sql:/data/application/init.sql
  votify-api:
    container_name: votify-api
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
    depends_on:
      - votify-postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - votify-postgres
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
